### ISSUE TITLE
blog.mozilla.org

### ISSUE THREAD

**Issue by Trustwbc** [dontobi/AdGuardHome-Lists#9]
https://blog.mozilla.org/
Also der Mozilla eigene Blog ist nicht erreichbar.

Regel(n)
||wpenginepowered.com^
dontobi Blacklist

Wäre super, wenn das überarbeitet werden würde. Danke

**Comment by dontobi** [comment]
Danke für den Hinweis. Hab die Whitelist angepasst. Mit dem nächsten Build ist die Änderung dann aktiv.
